---
- name: Create Vector user
  become: true
  ansible.builtin.user:
    name: vector
    system: yes
    create_home: no

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vector
    group: vector
    mode: 0755
  loop:
    - "{{ vector_config_dir }}"
    - "/var/lib/vector"

- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector.tar.gz"
    checksum: "sha256:{{ vector_checksum }}"

- name: Extract Vector
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/vector.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: ["--strip-components=2"]
    creates: "/usr/local/bin/vector"

- name: Deploy Vector config
  become: true
  ansible.builtin.template:
    src: "vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    owner: vector
    group: vector
    mode: 0640
  notify: restart vector

- name: Install systemd service
  become: true
  ansible.builtin.template:
    src: "vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
  notify: restart vector

- name: Enable Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    enabled: yes
    state: started